id: T0147
type: Technique

tactic: Reconnaissance

realm: 
  - CI/CDPosture

summary: Scan public CICD configurations for secrets and vulnerable actions

description: # REQUIRED - <key:value> - supports markdown

mitigations: # REQUIRED - <list> -reference to mitigation references
  - 

detections: # REQUIRED - <list> - reference to detection defintitions
  - 

subtechinques: # OPTIONAL <list> - reference to TechIDs
  - 

references: # OPTIONAL <list> - reference to attacks, articals, blogs etc...
  -

metadata: 
    state: draft

  