id: T0177
type: Technique

tactic: Impact

realm: 
  - CloudSecurity

summary: Misconfiguration of serverless workloads

description: # REQUIRED - <key:value> - supports markdown

mitigations: # REQUIRED - <list> -reference to mitigation references
  - 

detections: # REQUIRED - <list> - reference to detection defintitions
  - 

subtechinques: # OPTIONAL <list> - reference to TechIDs
  - 

references: # OPTIONAL <list> - reference to attacks, articals, blogs etc...
  -

metadata: 
    state: draft

  