id: D1170
type: Detection
summary: Configure audit logs to detect SQL injection
description: |
  Audit logs can help you to monitor application traffic in order to detect SQL injections.
  Audit logs can be configured on multiple layers, for example you can enable access logging for a web server or use your custom application events.
  Monitor for SQL-like constructions inside the application requests, also check for multiple error events in application logs.

references:
  - https://www.splunk.com/en_us/blog/security/sql-injections-the-splunk-method-for-auditing-your-application-security-model.html
  - https://www.acunetix.com/blog/articles/using-logs-to-investigate-a-web-application-attack/
  - https://documentation.wazuh.com/current/proof-of-concept-guide/detect-web-attack-sql-injection.html

metadata:
  - version: 0.1
  - state: draft
