id: D1180
type: Detection
summary: Configure audit logs to detect Command injection
description: |
  Audit logs can help you to monitor application traffic in order to detect Command Injections.
  Audit logs can be configured on multiple layers, for example you can enable access logging for a web server or use your custom application events.
  Monitor for shell commands constructions inside the application requests, also check for multiple error events in application logs.
  Create an allow-list of shell commands and monitor for the attempts of using the commands out of this list.

references:
  - https://www.cobalt.io/blog/a-pentesters-guide-to-command-injection
  - https://docs.rapid7.com/tcell/command-injection/

metadata:
  - version: 0.1
  - state: draft
