# Simple workflow for deploying static content to GitHub Pages
name: Build and Upload to S3

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create site content
        run: |
          python ./helpers/create_pbom_release.py --source content/oscar/ --dest .
          tar cvzf pbom_data.tar.gz pbom_data/
          ls -al
     
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pbom_data.tar.gz
          path: ./pbom_data.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: Release notes go here
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: pbom_data.tar.gz