name: Release PBOM artifacts

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create site content
        run: |
          python ./helpers/create_pbom_release.py --source content/oscar/ --dest .
          tar cvzf pbom_data.tar.gz pbom_data/
          ls -al
     
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pbom_data.tar.gz
          path: ./pbom_data.tar.gz
  
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::OSCAR_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release user firmware
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            pbom_data.tar.gz


     
